In [1]:
import sys
import numpy as np

print("Python: {}".format(sys.version_info[:]))
print('Numpy: {}'.format(np.__version__))

Python: (3, 6, 5, 'final', 0)
Numpy: 1.14.3


## Basics

### Initialization

In [2]:
# example of array > note the use of `[]`
# {{{np_init_01
np_ex = np.array([10,11,12,13,14,15,16,17,18,19,20])
# END}}}

In [3]:
# viewing information about the object
# {{{np_info_01
print("np_ex = {}".format(np_ex))
print("np_ex.shape = {}".format(np_ex.shape))
print("np_ex.dtype = {}".format(np_ex.dtype))
# END}}}

np_ex = [10 11 12 13 14 15 16 17 18 19 20]
np_ex.shape = (11,)
np_ex.dtype = int64


### Indexing

In [4]:
# {{{np_index_01
print("np_ex[3] = {}".format(np_ex[3]))
print("np_ex[-1] = {}".format(np_ex[-1]))
# END}}}

np_ex[3] = 13
np_ex[-1] = 20


In [5]:
# {{{np_index_02
print("np_ex[:] = {}".format(np_ex[:]))
print("np_ex[:3] = {}".format(np_ex[:3]))
print("np_ex[3:] = {}".format(np_ex[3:]))
# END}}}

np_ex[:] = [10 11 12 13 14 15 16 17 18 19 20]
np_ex[:3] = [10 11 12]
np_ex[3:] = [13 14 15 16 17 18 19 20]


In [6]:
# {{{np_index_03
print("np_ex[::2] = {}".format(np_ex[::2]))
print("np_ex[::-1] = {}".format(np_ex[::-1]))
print("np_ex[::-3] = {}".format(np_ex[::-3]))
# END}}}

np_ex[::2] = [10 12 14 16 18 20]
np_ex[::-1] = [20 19 18 17 16 15 14 13 12 11 10]
np_ex[::-3] = [20 17 14 11]


Using dtype to specify the type

In [7]:
# {{{np_dtypearg_01
np_ex = np.array([10,11,12,13,14,15,16,17,18,19,20], dtype=np.float64)
# END}}}
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex.dtype = float64


In [8]:
# what will it do by default if they're all floats?
np_ex = np.array([10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.])
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex.dtype = float64


Note what happens if just one is specified as a float

In [9]:
# {{{np_dtype_01
np_ex = np.array([10,11.,12,13,14,15,16,17,18,19,20])
# END}}}
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex.dtype = float64


### Types
Common types. Most common in **bold**. [Relevent documentation](https://docs.scipy.org/doc/numpy/user/basics.types.html)

Boolean

- **`bool`**

Signed Int

- `int8` _(-128, 127)_
- `int16` _(-32768, 32767)_
- `int32`  _(-2147483648, 2147483647)_
- **`int64`** _(-9223372036854775808, 9223372036854775807)_

Unsigned Int

- `uint8` _(0, 255)_
- `uint16` _(0, 65535)_
- `uint32`  _(0, 4294967295)_
- `uint64` _(0, 18446744073709551615)_

Floats

- `float16` "half precision"
- `float32` "single precision"
- **`float64`** "double precision"

## special initializations

### zeros

In [10]:
# initialize by `shape` keyword
# {{{np_zeros_01
np_ex = np.zeros(shape=(3,6))
# END}}}
print("np_ex = \n{}".format(np_ex))
print("np_ex.shape = {}".format(np_ex.shape))
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex = 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
np_ex.shape = (3, 6)
np_ex.dtype = float64


### ones

In [11]:
# {{{np_ones_01
np_ex = np.ones((3,6))
# END}}}
print("np_ex = \n{}".format(np_ex))
print("np_ex.shape = {}".format(np_ex.shape))
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex = 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
np_ex.shape = (3, 6)
np_ex.dtype = float64


### empty 

The output will vary

In [12]:
# {{{np_empty_01
np_ex = np.empty((2,2))
# END}}}
print("np_ex = \n{}".format(np_ex))
print("np_ex.shape = {}".format(np_ex.shape))
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex = 
[[2.72876563e+114 5.58294180e-322]
 [4.66005481e-310 4.66005485e-310]]
np_ex.shape = (2, 2)
np_ex.dtype = float64


### eye

Identity matrix

In [13]:
# {{{np_eye_01
np_ex = np.eye(3)
# END}}}
print("np_ex = \n{}".format(np_ex))
print("np_ex.shape = {}".format(np_ex.shape))
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np_ex.shape = (3, 3)
np_ex.dtype = float64


### full

Constant

In [14]:
# {{{np_full_01
np_ex = np.full((3,3), 9)
# END}}}
print("np_ex = \n{}".format(np_ex))
print("np_ex.shape = {}".format(np_ex.shape))
print("np_ex.dtype = {}".format(np_ex.dtype))

np_ex = 
[[9 9 9]
 [9 9 9]
 [9 9 9]]
np_ex.shape = (3, 3)
np_ex.dtype = int64


## Reshape

.arange will create a 1D array in the range [0,value)

In [15]:
# 1D vs 2D vs 3D
# {{{np_arange_01
vals_1D = np.arange(27)
# END}}}
print("vals_1D = \n{}".format(vals_1D))
print("vals_1D.shape = {}".format(vals_1D.shape))

vals_1D = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
vals_1D.shape = (27,)


In [16]:
# {{{np_reshape_01
vals_2D = vals_1D.reshape(9,3)
# END}}}
print("vals_2D = \n{}".format(vals_2D))
print("vals_2D.shape = {}".format(vals_2D.shape))

vals_2D = 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]
vals_2D.shape = (9, 3)


In [17]:
# {{{np_reshape_02
vals_2D = vals_1D.reshape(3,9)
# END}}}
print("vals_2D = \n{}".format(vals_2D))
print("vals_2D.shape = {}".format(vals_2D.shape))

vals_2D = 
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
vals_2D.shape = (3, 9)


In [18]:
# {{{np_reshape_03
vals_3D = vals_1D.reshape(3,3,3)
# END}}}
print("vals_3D = \n{}".format(vals_3D))
print("vals_3D.shape = {}".format(vals_3D.shape))

vals_3D = 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
vals_3D.shape = (3, 3, 3)


### Convert list to numpy

Convert list to numpy array

In [19]:
# {{{np_asarray_01
some_list = [1,2,3,4,5,6,7]
list_as_arr = np.asarray(some_list)
# END}}}
print("some_list: {}".format(some_list))
print("list_as_arr: {}".format(list_as_arr))
print("list_as_arr.shape: {}".format(list_as_arr.shape))

some_list: [1, 2, 3, 4, 5, 6, 7]
list_as_arr: [1 2 3 4 5 6 7]
list_as_arr.shape: (7,)
