In [1]:
import sys
import numpy as np

print("Python: {}".format(sys.version_info[:]))
print('Numpy: {}'.format(np.__version__))

Python: (3, 6, 3, 'final', 0)
Numpy: 1.13.3


## argmax

In [2]:
np_1d = np.arange(9)
np_2d = np.arange(9).reshape(3,3)
np_3d = np.arange(27).reshape(3,3,3)

print("np_1d; \n{}".format(np_1d))
print("np_1d.shape = {}".format(np_1d.shape))

print("\nnp_2d; \n{}".format(np_2d))
print("np_2d.shape = {}".format(np_2d.shape))

print("\nnp_3d; \n{}".format(np_3d))
print("np_3d.shape = {}".format(np_3d.shape))

np_1d; 
[0 1 2 3 4 5 6 7 8]
np_1d.shape = (9,)

np_2d; 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
np_2d.shape = (3, 3)

np_3d; 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
np_3d.shape = (3, 3, 3)


In [3]:
print("1D")
argmax_1d = np_1d.argmax(axis=0)
print("argmax, axis=0: {}".format(argmax_1d))

print("\n2D")
argmax_2d_a0 = np_2d.argmax(axis=0)
argmax_2d_a1 = np_2d.argmax(axis=1)
print("argmax, axis=0: {}".format(argmax_2d_a0))
print("argmax, axis=1: {}".format(argmax_2d_a1))

print("\n3D")
argmax_3d_a0 = np_3d.argmax(axis=0)
argmax_3d_a1 = np_3d.argmax(axis=1)
argmax_3d_a2 = np_3d.argmax(axis=2)
print("argmax, axis=0: \n{}".format(argmax_3d_a0))
print("argmax, axis=1: \n{}".format(argmax_3d_a1))
print("argmax, axis=2: \n{}".format(argmax_3d_a2))

1D
argmax, axis=0: 8

2D
argmax, axis=0: [2 2 2]
argmax, axis=1: [2 2 2]

3D
argmax, axis=0: 
[[2 2 2]
 [2 2 2]
 [2 2 2]]
argmax, axis=1: 
[[2 2 2]
 [2 2 2]
 [2 2 2]]
argmax, axis=2: 
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
# alternate view
np_2d = np.array([[7,1,9],[1,3,5],[6,2,1]])
print("np_2d; \n{}".format(np_2d))
print("np_2d.shape = {}".format(np_2d.shape))

argmax_2d_a0 = np_2d.argmax(axis=0)
argmax_2d_a1 = np_2d.argmax(axis=1)
# compare values in each displayed "column"
print("\nargmax, axis=0: {}".format(argmax_2d_a0))
print("({},{},{})={}, ({},{},{})={}, ({},{},{})={}".format(np_2d[0][0], np_2d[1][0], 
                                                  np_2d[2][0], argmax_2d_a0[0],
                                                  np_2d[0][1], np_2d[1][1], 
                                                  np_2d[2][1], argmax_2d_a0[1],
                                                  np_2d[0][2], np_2d[1][2], 
                                                  np_2d[2][2], argmax_2d_a0[2]))

# compare values in each displayed "row"
print("\nargmax, axis=1: {}".format(argmax_2d_a1))
print("({},{},{})={}, ({},{},{})={}, ({},{},{})={}".format(np_2d[0][0], np_2d[0][1], 
                                                  np_2d[0][2], argmax_2d_a1[0],
                                                  np_2d[1][0], np_2d[1][1], 
                                                  np_2d[1][2], argmax_2d_a1[1],
                                                  np_2d[2][0], np_2d[2][1], 
                                                  np_2d[2][2], argmax_2d_a1[2]))

np_2d; 
[[7 1 9]
 [1 3 5]
 [6 2 1]]
np_2d.shape = (3, 3)

argmax, axis=0: [0 1 0]
(7,1,6)=0, (1,3,2)=1, (9,5,1)=0

argmax, axis=1: [2 2 0]
(7,1,9)=2, (1,3,5)=2, (6,2,1)=0


## expand_dims

In [5]:
np_a = np.arange(9).reshape(3,3)
print("np_a; \n{}".format(np_a))
print("np_a.shape = {}".format(np_a.shape))

np_b = np.expand_dims(np_a, axis=0)
print("\nnp_b = np.expand_dims(np_a, axis=0); \n{}".format(np_b))
print("np_b.shape = {}".format(np_b.shape))

np_c = np.expand_dims(np_a, axis=1)
print("\nnp_c = np.expand_dims(np_a, axis=1); \n{}".format(np_c))
print("np_c.shape = {}".format(np_c.shape))

np_d = np.expand_dims(np_a, axis=-1)
print("\nnp_d = np.expand_dims(np_a, axis=-1); \n{}".format(np_d))
print("np_d.shape = {}".format(np_d.shape))

np_a; 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
np_a.shape = (3, 3)

np_b = np.expand_dims(np_a, axis=0); 
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
np_b.shape = (1, 3, 3)

np_c = np.expand_dims(np_a, axis=1); 
[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
np_c.shape = (3, 1, 3)

np_d = np.expand_dims(np_a, axis=-1); 
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
np_d.shape = (3, 3, 1)


## means and standard deviations

In [6]:
np_2d = np.array([[0,0,3],[0,9,3],[1,0,3]])
print("np_2d; \n{}".format(np_2d))
print("np_2d.shape = {}".format(np_2d.shape))

mean_0 = np.mean(np_2d, axis=0)
print("np.mean(np_2d, axis=0) = {}".format(mean_0))
mean_1 = np.mean(np_2d, axis=1)
print("np.mean(np_2d, axis=1) = {}".format(mean_1))

np_2d; 
[[0 0 3]
 [0 9 3]
 [1 0 3]]
np_2d.shape = (3, 3)
np.mean(np_2d, axis=0) = [ 0.33333333  3.          3.        ]
np.mean(np_2d, axis=1) = [ 1.          4.          1.33333333]


## minimum and maximum

In [7]:
np_2d = np.array([[0,0,3],[0,9,3],[1,0,3]])
print("np_2d; \n{}".format(np_2d))
print("np_2d.shape = {}".format(np_2d.shape))

min_0 = np.min(np_2d, axis=0)
print("\nnp.min(np_2d, axis=0) = {}".format(min_0))
min_1 = np.min(np_2d, axis=1)
print("np.min(np_2d, axis=1) = {}".format(min_1))

max_0 = np.max(np_2d, axis=0)
print("\nnp.max(np_2d, axis=0) = {}".format(max_0))
max_1 = np.max(np_2d, axis=1)
print("np.max(np_2d, axis=1) = {}".format(max_1))

np_2d; 
[[0 0 3]
 [0 9 3]
 [1 0 3]]
np_2d.shape = (3, 3)

np.min(np_2d, axis=0) = [0 0 3]
np.min(np_2d, axis=1) = [0 0 0]

np.max(np_2d, axis=0) = [1 9 3]
np.max(np_2d, axis=1) = [3 9 3]


## Copy (deep vs shallow)

### Shallow
**It is important to note the difference between a shallow and deep copy in numpy.  This has previously fooled me and lead to a difficult bug to track down.**

In [8]:
base_matrix = np.arange(4).reshape(2,2)
print("base_matrix; \n{}".format(base_matrix))
print("base_matrix.shape = {}".format(base_matrix.shape))

shallow_copy = base_matrix
print("\nshallow_copy; \n{}".format(shallow_copy))

shallow_copy *= 2
print("\nshallow_copy *= 2; \n{}".format(shallow_copy))

# Base changes!!!!!
print("\nbase_matrix; \n{}".format(base_matrix))

base_matrix; 
[[0 1]
 [2 3]]
base_matrix.shape = (2, 2)

shallow_copy; 
[[0 1]
 [2 3]]

shallow_copy *= 2; 
[[0 2]
 [4 6]]

base_matrix; 
[[0 2]
 [4 6]]


In [9]:
base_matrix = np.arange(4).reshape(2,2)
print("base_matrix; \n{}".format(base_matrix))
print("base_matrix.shape = {}".format(base_matrix.shape))

shallow_copy = base_matrix
print("\nshallow_copy; \n{}".format(shallow_copy))

base_matrix *= 2
print("\nbase_matrix *= 2; \n{}".format(base_matrix))

# Shallow copy changes!!!
print("\nshallow_copy; \n{}".format(shallow_copy))

base_matrix; 
[[0 1]
 [2 3]]
base_matrix.shape = (2, 2)

shallow_copy; 
[[0 1]
 [2 3]]

base_matrix *= 2; 
[[0 2]
 [4 6]]

shallow_copy; 
[[0 2]
 [4 6]]


### Deep copy

In [10]:
base_matrix = np.arange(4).reshape(2,2)
print("base_matrix; \n{}".format(base_matrix))
print("base_matrix.shape = {}".format(base_matrix.shape))

deep_copy = base_matrix.copy()
print("\ndeep_copy; \n{}".format(deep_copy))

deep_copy *= 2
print("\ndeep_copy *= 2; \n{}".format(deep_copy))

# Base doesn't change
print("\nbase_matrix; \n{}".format(base_matrix))

base_matrix; 
[[0 1]
 [2 3]]
base_matrix.shape = (2, 2)

deep_copy; 
[[0 1]
 [2 3]]

deep_copy *= 2; 
[[0 2]
 [4 6]]

base_matrix; 
[[0 1]
 [2 3]]


In [11]:
base_matrix = np.arange(4).reshape(2,2)
print("base_matrix; \n{}".format(base_matrix))
print("base_matrix.shape = {}".format(base_matrix.shape))

deep_copy = base_matrix.copy()
print("\ndeep_copy; \n{}".format(deep_copy))

base_matrix *= 2
print("\nbase_matrix *= 2; \n{}".format(base_matrix))

# deep doesn't change
print("\ndeep_copy; \n{}".format(deep_copy))

base_matrix; 
[[0 1]
 [2 3]]
base_matrix.shape = (2, 2)

deep_copy; 
[[0 1]
 [2 3]]

base_matrix *= 2; 
[[0 2]
 [4 6]]

deep_copy; 
[[0 1]
 [2 3]]
