# tf.one_hot()

In [1]:
# DL framework
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

from datetime import datetime

# common packages
import numpy as np
import os # handling file i/o
import sys
import math
import time # timing epochs

# for ordered dict when building layer components
import collections

# plotting pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import pyplot
from matplotlib import colors # making colors consistent
from mpl_toolkits.axes_grid1 import make_axes_locatable # colorbar helper

# read image
from scipy.misc import imread
# + data augmentation
from scipy import ndimage
from scipy import misc

# used for manually saving best params
import pickle

# for shuffling data batches
from sklearn.utils import shuffle

# const
SEED = 42

# Helper to make the output consistent
def reset_graph(seed=SEED):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# helper to create dirs if they don't already exist
def maybe_create_dir(dir_path):
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
        print("{} createed".format(dir_path))
    else:
        print("{} already exists".format(dir_path))
    
# set log level to supress messages, unless an error
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Important Version information
print("Python: {}".format(sys.version_info[:]))
print('TensorFlow: {}'.format(tf.__version__))

# Check if using GPU
if not tf.test.gpu_device_name():
    print('No GPU found')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
    
reset_graph()

Python: (3, 5, 4, 'final', 0)
TensorFlow: 1.5.0-dev20171220
No GPU found


In [2]:
example_a = np.asarray([0,1,0,1,2,3])
example_a_enc = tf.one_hot(example_a, 
                           depth=int(np.max(example_a)+1))
print(example_a_enc)

tf.Tensor(
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]], shape=(6, 4), dtype=float32)


In [3]:
example_b = np.asarray([0,1.2,0,1,1,2,3.6])
# decimal values will be truncated, not rounded
example_b_enc = tf.one_hot(example_b, depth=np.max(example_b)+1)
print(example_b_enc)

tf.Tensor(
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]], shape=(7, 4), dtype=float32)


In [4]:
# order is not important. meaning index 0 in `example_c` is 2,
# but that doens't mean index 0 in the one hot encoded vector 
# will represent 2
example_c = np.asarray([2,3,0,1,-1,2,3.6])
ex_c_depth = np.max(example_c) + 1 - np.min(example_c)
print(ex_c_depth) # [-1, 0, 1, 2, 3]
example_c_enc = tf.one_hot(example_c, depth=ex_c_depth)
# one hot labels: [0, 1, 2, 3, 4]
print(example_c_enc)

5.6
tf.Tensor(
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]], shape=(7, 5), dtype=float32)


In [5]:
# one hot labels start at 0
example_d = np.asarray([2,1,2,1,1,1,1])
ex_d_depth = np.max(example_d)+1
print(ex_d_depth) # [0, 1, 2]
example_d_enc = tf.one_hot(example_d, depth=ex_d_depth)
print(example_d_enc)

3
tf.Tensor(
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]], shape=(7, 3), dtype=float32)
