# Fizz Buzz

### Resources

This notebook is inspired/created by/from this [blog post](http://joelgrus.com/2016/05/23/fizz-buzz-in-tensorflow/) by Joel Grus.

### Note:

This isn't exactly a *serious* solution to a problem, but it's interesting+fun

In [1]:
# NOTE: this is a custom cell that contains the common imports I personally 
# use these may/may not be necessary for the following examples

# DL framework
import tensorflow as tf

from datetime import datetime

# common packages
import numpy as np
import os # handling file i/o
import sys
import math
import time # timing epochs
import random

# for ordered dict when building layer components
import collections

# plotting pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import pyplot
from matplotlib import colors # making colors consistent
from mpl_toolkits.axes_grid1 import make_axes_locatable # colorbar helper


# from imageio import imread # read image from disk
# + data augmentation
from scipy import ndimage
from scipy import misc


import pickle # manually saving best params
from sklearn.utils import shuffle # shuffling data batches
from tqdm import tqdm # display training progress bar

# const
SEED = 42

# Helper to make the output consistent
def reset_graph(seed=SEED):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# helper to create dirs if they don't already exist
def maybe_create_dir(dir_path):
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
        print("{} created".format(dir_path))
    else:
        print("{} already exists".format(dir_path))
    
def make_standard_dirs(saver=True, best_params=True, tf_logs=True):
    # `saver/` will hold tf saver files
    maybe_create_dir("saver")
    # `best_params/` will hold a serialized version of the best params
    # I like to keep this as a backup in case I run into issues with
    # the saver files
    maybe_create_dir("best_params")
    # `tf_logs/` will hold the logs that will be visable in tensorboard
    maybe_create_dir("tf_logs")

    
# set tf log level to supress messages, unless an error
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Important Version information
print("Python: {}".format(sys.version_info[:]))
print('TensorFlow: {}'.format(tf.__version__))

# Check if using GPU
if not tf.test.gpu_device_name():
    print('No GPU')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
    
reset_graph()

Python: (3, 5, 4, 'final', 0)
TensorFlow: 1.6.0-dev20180105
No GPU


In [2]:
make_standard_dirs()

saver already exists
best_params already exists
tf_logs already exists


In [3]:
### Clean all logs
## WARNING! You likely don't want to do this (but if you do, this is a convenient call)
# !rm -r -f ./tf_logs/*

In [4]:
# these two functions (get_model_params and restore_model_params) are 
# ad[a|o]pted from; 
# https://github.com/ageron/handson-ml/blob/master/11_deep_learning.ipynb
def get_model_params():
    global_vars = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
    return {global_vars.op.name: value for global_vars, value in 
            zip(global_vars, tf.get_default_session().run(global_vars))}

def restore_model_params(model_params, g, sess):
    gvar_names = list(model_params.keys())
    assign_ops = {gvar_name: g.get_operation_by_name(gvar_name + "/Assign")
                  for gvar_name in gvar_names}
    init_values = {gvar_name: assign_op.inputs[1] for gvar_name, assign_op in assign_ops.items()}
    feed_dict = {init_values[gvar_name]: model_params[gvar_name] for gvar_name in gvar_names}
    sess.run(assign_ops, feed_dict=feed_dict)

# these two functions are used to manually save the best
# model params to disk
def save_obj(obj, name):
    with open('best_params/'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name):
    with open('best_params/' + name + '.pkl', 'rb') as f:
        return pickle.load(f)

## Create Data

In [5]:
BEST_PARAMS_PATH = "best_params"

In [162]:
def fizz_buzz_encode(i):
    # one-hot representation of representations
    # fizz, buzz, fizzbuzz, and NA
    if i % 15 == 0:
        return np.array([0,0,0,1]) # fizzbuzz
    elif i % 5 == 0:
        return np.array([0,1,0,0]) # fizz
    elif i % 3 == 0:
        return np.array([0,0,1,0]) # buzz
    else:
        return np.array([1,0,0,0]) # none/NA


In [198]:
def fizz_buzz_decode(enc):
    if enc[1] == 1:
        return "fizz"
    elif enc[2] == 1:
        return "buzz"
    elif enc[3] == 1:
        return "fizzbuzz"
    
def class_decode(enc):
    if enc[1] == 1:
        return 1
    elif enc[2] == 1:
        return 2
    elif enc[3] == 1:
        return 3
    else:
        return 0
    
def ind_class_decode(ind):
    if ind == 0:
        return 'None'
    elif ind == 1:
        return 'Fizz'
    elif ind == 2:
        return 'Buzz'
    elif ind == 3:
        return 'FizzBuzz'

In [238]:
def create_hyper_params():
    hypms = {}
    hypms['n_epochs'] = 10000
    hypms['batch_size'] = 128
    hypms['init_lr'] = 1e-4
    #hypms['fc_dropout'] = 0.5
    hypms['n_input'] = 12
    hypms['n_classes'] = 4
    hypms['n_hidden'] = 256
    return hypms
hypms = create_hyper_params()

In [9]:
NUM_DIGITS = 12
tr_X = np.arange(101,2**NUM_DIGITS)
tr_y = np.array([fizz_buzz_encode(i) for i in tr_X])

In [10]:
print("{}; {}->{}".format(tr_X[1], tr_y[1], fizz_buzz_decode(tr_y[1])))

102; [0 0 1 0]->buzz


## Let's convert to binary

In [11]:
def binary_encode(i, NUM_DIGITS):
    bs = ("{0:0" + str(NUM_DIGITS) + "b}").format(i) # convert to bin rep
    bsl = [int(i) for i in bs] # convert bin rep to list of int
    return np.array(bsl)
#print("{}->{}".format(10, binary_encode(10, 10)))

def binary_decode(enc):
    bin_str = "".join([str(i) for i in enc])
    return int(bin_str, 2)

In [12]:
tr_X = np.array([binary_encode(i, NUM_DIGITS) for i in tr_X])

we now have tr_X and tr_y where;

```tr_X = binary representation of int value
tr_y = encoded label; ie [0 0 1 0] = "buzz
```

## Build graph

In [13]:
tr_X, tr_y = shuffle(tr_X, tr_y, random_state=42)
X_tr = tr_X[500:]
y_tr = tr_y[500:]
X_val = tr_X[:500]
y_val = tr_y[:500]

In [14]:
f,b,fb,n = 0,0,0,0
for vec in y_tr:
    if vec[3] == 1:
        fb += 1
    elif vec[2] == 1:
        b += 1
    elif vec[1] == 1:
        f += 1
    elif vec[0] == 1:
        n += 1
class_weights = np.array([n, f, b, fb], dtype=np.float32) / len(y_tr)
print(class_weights)
# unique, counts = np.unique(y_tr, return_counts=True, axis=1)
# for i in unique:
#     print("{} -> {}".format(unique[i], counts[i]))

[ 0.53218883  0.13218884  0.26752505  0.06809728]


In [145]:
class_weights = np.array([1,100,200,300], dtype=np.float32)

In [150]:
from sklearn.utils import class_weight

In [171]:
jj = np.array([class_decode(i) for i in y_tr])

In [220]:
jack = class_weight.compute_class_weight('balanced', np.array([0,1,2,3]), jj)
#jack = class_weight.compute_class_weight(None, np.array([0,1,2,3]), jj)

In [222]:
print(jack)

[ 0.46975806  1.89123377  0.93449198  3.67121849]


In [223]:
X_test = np.array([binary_encode(i, hypms['n_input']) for i in range(100)])
y_test = np.array([fizz_buzz_encode(i)                for i in range(100)])

In [224]:
for i in range(16):
    print("{}: -> {}".format(binary_decode(X_test[i]), fizz_buzz_decode(y_test[i])))

0: -> fizzbuzz
1: -> None
2: -> None
3: -> buzz
4: -> None
5: -> fizz
6: -> buzz
7: -> None
8: -> None
9: -> buzz
10: -> fizz
11: -> None
12: -> buzz
13: -> None
14: -> None
15: -> fizzbuzz


In [226]:
he_init = tf.contrib.layers.variance_scaling_initializer()

In [239]:
def build_graph():
    global class_weights
    g = tf.Graph()
    with g.as_default():
        global hypms
        with tf.name_scope("model"):
            # inputs
            with tf.name_scope("inputs"):
                X = tf.placeholder(tf.float32, shape=[None, hypms['n_input']], name="data")
                y = tf.placeholder(tf.float32, shape=[None, hypms['n_classes']], name="labels") # Target

            with tf.name_scope("layers"):
                h_01 = tf.layers.dense(X, 256, name="dense_01", kernel_initializer=he_init, activation=tf.nn.elu)
                h_02 = tf.layers.dense(h_01, 128, name="dense_02", kernel_initializer=he_init, activation=tf.nn.elu)
                h_03 = tf.layers.dense(h_02, 64, name="dense_03", kernel_initializer=he_init, activation=tf.nn.elu)
                h_04 = tf.layers.dense(h_03, 32, name="dense_04", kernel_initializer=he_init, activation=tf.nn.elu)

            with tf.name_scope("output"):
                logits = tf.layers.dense(h_04, hypms['n_classes'], name="logits")
                cls_weight = tf.constant([[jack[0],
                                           jack[1],
                                           jack[2],
                                           jack[3]]])
                weight_per_label = tf.transpose(tf.matmul(y, tf.transpose(cls_weight)))
                Y_proba = tf.nn.softmax(logits, name="Y_proba")
                print(Y_proba)

            with tf.name_scope("train"):
                xent = tf.nn.softmax_cross_entropy_with_logits(logits=logits, 
                                                               labels=y)
                xentropy = weight_per_label*xent
                #print(tmp_xent)
                #data_tf = tf.convert_to_tensor(cls_wight_vec, np.float32)
                #print(data_tf)
                #xentropy = tmp_xent*class_weights
                batch_loss = tf.reduce_mean(xentropy)
                optimizer = tf.train.AdamOptimizer(learning_rate=hypms['init_lr'])
                training_op = optimizer.minimize(batch_loss)
        with tf.name_scope("aux"):
            with tf.name_scope("save_session"):
                init_global = tf.global_variables_initializer()
                init_local = tf.local_variables_initializer()
                saver = tf.train.Saver()
            with tf.name_scope("metrics"):
                with tf.name_scope("common"):
                    y_true_cls = tf.argmax(y,1)
                    y_pred_cls = tf.argmax(Y_proba,1)
                    correct_prediction = tf.equal(y_pred_cls, y_true_cls, name="correct_predictions")
                    batch_acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
                with tf.name_scope("train_metrics") as scope:
                    train_auc, train_auc_update = tf.metrics.auc(labels=y, predictions=Y_proba)
                    train_acc, train_acc_update = tf.metrics.accuracy(labels=y_true_cls, predictions=y_pred_cls)
                    train_acc_vars = tf.contrib.framework.get_variables(scope, collection=tf.GraphKeys.LOCAL_VARIABLES)
                    train_met_reset_op = tf.variables_initializer(train_acc_vars, name="train_met_reset_op")
                with tf.name_scope("val_metrics") as scope:
                    val_auc, val_auc_update = tf.metrics.auc(labels=y, predictions=Y_proba)
                    val_acc, val_acc_update = tf.metrics.accuracy(labels=y_true_cls, predictions=y_pred_cls)
                    val_acc_vars = tf.contrib.framework.get_variables(scope, collection=tf.GraphKeys.LOCAL_VARIABLES)
                    val_met_reset_op = tf.variables_initializer(val_acc_vars, name="val_met_reset_op")
                with tf.name_scope("test_metrics") as scope:
                    test_auc, test_auc_update = tf.metrics.auc(labels=y, predictions=Y_proba)
                    test_acc, test_acc_update = tf.metrics.accuracy(labels=y_true_cls, predictions=y_pred_cls)
                    test_acc_vars = tf.contrib.framework.get_variables(scope, collection=tf.GraphKeys.LOCAL_VARIABLES)
                    test_acc_reset_op = tf.variables_initializer(test_acc_vars, name="test_met_reset_op")

                # =============================================== loss 
                with tf.name_scope("train_loss_eval") as scope:
                    train_mean_loss, train_mean_loss_update = tf.metrics.mean(batch_loss)
                    train_loss_vars = tf.contrib.framework.get_variables(scope, collection=tf.GraphKeys.LOCAL_VARIABLES)
                    train_loss_reset_op = tf.variables_initializer(train_loss_vars, name="train_loss_reset_op")
                with tf.name_scope("val_loss_eval") as scope:
                    val_mean_loss, val_mean_loss_update = tf.metrics.mean(batch_loss)
                    val_loss_vars = tf.contrib.framework.get_variables(scope, collection=tf.GraphKeys.LOCAL_VARIABLES)
                    val_loss_reset_op = tf.variables_initializer(val_loss_vars, name="val_loss_reset_op")
                with tf.name_scope("test_loss_eval")as scope:
                    test_mean_loss, test_mean_loss_update = tf.metrics.mean(batch_loss)
                    test_loss_vars = tf.contrib.framework.get_variables(scope, collection=tf.GraphKeys.LOCAL_VARIABLES)
                    test_loss_reset_op = tf.variables_initializer(test_loss_vars, name="test_loss_rest_op")
                
            with tf.name_scope("tensorboard_writer") as scope:
                epoch_train_loss_scalar = tf.summary.scalar('train_epoch_loss', train_mean_loss)
                epoch_train_acc_scalar = tf.summary.scalar('train_epoch_acc', train_acc)
                epoch_train_auc_scalar = tf.summary.scalar('train_epoch_auc', train_auc)
                epoch_train_write_op = tf.summary.merge([epoch_train_loss_scalar, epoch_train_acc_scalar, epoch_train_auc_scalar], name="epoch_train_write_op")

                # ===== epoch, validation
                epoch_validation_loss_scalar = tf.summary.scalar('validation_epoch_loss', val_mean_loss)
                epoch_validation_acc_scalar = tf.summary.scalar('validation_epoch_acc', val_acc)
                epoch_validation_auc_scalar = tf.summary.scalar('validation_epoch_auc', val_auc)
                epoch_validation_write_op = tf.summary.merge([epoch_validation_loss_scalar, epoch_validation_acc_scalar, epoch_validation_auc_scalar], name="epoch_validation_write_op")
        
        # --- create collections
        for node in (saver, init_global, init_local):
            g.add_to_collection("save_init", node)
        for node in (X, y, training_op):
            g.add_to_collection("main_ops", node)
        for node in (Y_proba, y_true_cls, y_pred_cls, correct_prediction):
            g.add_to_collection("preds", node)
        for node in (train_auc, train_auc_update, train_acc, train_acc_update, train_met_reset_op):
            g.add_to_collection("train_metrics", node)
        for node in (val_auc, val_auc_update, val_acc, val_acc_update, val_met_reset_op):
            g.add_to_collection("val_metrics", node)
        for node in (test_auc, test_auc_update, test_acc, test_acc_update, test_acc_reset_op):
            g.add_to_collection("test_metrics", node)
        for node in (train_mean_loss, train_mean_loss_update, train_loss_reset_op):
            g.add_to_collection("train_loss", node)
        for node in (val_mean_loss, val_mean_loss_update, val_loss_reset_op):
            g.add_to_collection("val_loss", node)
        for node in (test_mean_loss, test_mean_loss_update, test_loss_reset_op):
            g.add_to_collection("test_loss", node)
        g.add_to_collection("logits", logits)
        for node in (epoch_train_write_op, epoch_validation_write_op):
                g.add_to_collection("tensorboard", node)
                

    return g

In [240]:
def train_graph(g):
    global hypms
    global BEST_PARAMS_PATH
    global X_tr, y_tr
    saver, init_global, init_local = g.get_collection("save_init")
    X, y, training_op = g.get_collection("main_ops")
    preds, y_true_cls, y_pred_cls, _ = g.get_collection("preds")
    train_auc, train_auc_update, train_acc, train_acc_update, train_met_reset_op = g.get_collection("train_metrics")
    val_auc, val_auc_update, val_acc, val_acc_update, val_met_reset_op = g.get_collection("val_metrics")
    train_mean_loss, train_mean_loss_update, train_loss_reset_op = g.get_collection("train_loss")
    val_mean_loss, val_mean_loss_update, val_loss_reset_op = g.get_collection("val_loss")
    epoch_train_write_op, epoch_validation_write_op = g.get_collection("tensorboard")
    train_writer = tf.summary.FileWriter(os.path.join("tf_logs","train"))
    val_writer = tf.summary.FileWriter(os.path.join("tf_logs","validation"))
    best_val_loss = np.inf
    
    with tf.Session(graph=g) as sess:
        sess.run([init_global, init_local])
        #train_writer.add_summary
        for e in tqdm(range(1,hypms['n_epochs']+1)):
            sess.run([val_met_reset_op,val_loss_reset_op,train_met_reset_op,train_loss_reset_op])
            
            X_tr, y_tr = shuffle(X_tr, y_tr, random_state=42)
            for iteration in range(len(X_tr) // hypms['batch_size']):
                # last batch is ignored (but the above shuffle will integrate it
                # in the next round)
                low_i = iteration*hypms['batch_size']
                high_i = (iteration+1)*hypms['batch_size']
                X_batch = X_tr[low_i:high_i]     
                y_batch = y_tr[low_i:high_i]
                
                sess.run([training_op, train_auc_update, train_acc_update, train_mean_loss_update], 
                         feed_dict={X:X_batch, y:y_batch})

            # write average for epoch + graph information
            # run options is not working as expected -- my directory link must be broken
            #run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
            run_metadata = tf.RunMetadata()
            summary = sess.run(epoch_train_write_op, run_metadata=run_metadata)
            train_writer.add_run_metadata(run_metadata, str(e)) # not sure on this..
            train_writer.add_graph(g)
            train_writer.add_summary(summary, e)
            train_writer.flush()

            # run validation
            for iteration in range(len(X_val) // hypms['batch_size']):
                low_i = iteration*hypms['batch_size']
                high_i = (iteration+1)*hypms['batch_size']
                Xvb = X_val[low_i:high_i]     
                yvb = y_val[low_i:high_i]
                sess.run([val_auc_update, val_acc_update, val_mean_loss_update], 
                                  feed_dict={X:Xvb, y:yvb})

            Xvb = X_val[high_i:]
            yvb = y_val[high_i:]
            if len(Xvb) > 0:
                sess.run([val_auc_update, val_acc_update, val_mean_loss_update], 
                         feed_dict={X: Xvb, y: yvb})

                
            # check for (and save) best validation params here
            cur_loss, cur_acc = sess.run([val_mean_loss, val_acc])
            if cur_loss < best_val_loss:
                best_val_loss = cur_loss
                best_params = get_model_params()
                save_obj(best_params, BEST_PARAMS_PATH)
                print("best params saved: val acc: {:.3f}% val loss: {:.4f}".format(cur_acc*100, cur_loss))
            
            summary = sess.run(epoch_validation_write_op) 
            val_writer.add_summary(summary, e)
            val_writer.flush()

        # close writers
        train_writer.close()
        val_writer.close()
    return sess

In [241]:
reset_graph()
hypms = create_hyper_params()
g = build_graph()
sess = train_graph(g)

Tensor("model/output/Y_proba:0", shape=(?, 4), dtype=float32)


  0%|          | 1/10000 [00:00<1:16:30,  2.18it/s]

best params saved: val acc: 23.800% val loss: 1.5548


  0%|          | 2/10000 [00:00<1:07:47,  2.46it/s]

best params saved: val acc: 26.800% val loss: 1.4464


  0%|          | 3/10000 [00:01<1:06:30,  2.51it/s]

best params saved: val acc: 21.200% val loss: 1.4316


  0%|          | 4/10000 [00:01<1:06:01,  2.52it/s]

best params saved: val acc: 23.200% val loss: 1.4264


  0%|          | 5/10000 [00:01<1:04:07,  2.60it/s]

best params saved: val acc: 23.600% val loss: 1.4219


  0%|          | 9/10000 [00:03<1:00:53,  2.73it/s]

best params saved: val acc: 19.800% val loss: 1.4216


  1%|          | 99/10000 [00:30<51:31,  3.20it/s]  

best params saved: val acc: 18.000% val loss: 1.4186


  1%|          | 101/10000 [00:31<51:46,  3.19it/s]

best params saved: val acc: 16.200% val loss: 1.4146


  1%|          | 104/10000 [00:32<52:07,  3.16it/s]

best params saved: val acc: 18.800% val loss: 1.4086


  1%|          | 105/10000 [00:33<52:10,  3.16it/s]

best params saved: val acc: 17.200% val loss: 1.4054


  1%|          | 107/10000 [00:34<52:35,  3.14it/s]

best params saved: val acc: 19.600% val loss: 1.3945


  1%|          | 108/10000 [00:34<52:39,  3.13it/s]

best params saved: val acc: 19.200% val loss: 1.3887


  1%|          | 110/10000 [00:35<52:41,  3.13it/s]

best params saved: val acc: 18.000% val loss: 1.3784


  1%|          | 111/10000 [00:35<52:49,  3.12it/s]

best params saved: val acc: 17.600% val loss: 1.3759


  1%|          | 113/10000 [00:36<53:02,  3.11it/s]

best params saved: val acc: 21.200% val loss: 1.3670


  1%|          | 116/10000 [00:37<53:10,  3.10it/s]

best params saved: val acc: 22.400% val loss: 1.3542


  1%|          | 117/10000 [00:37<53:18,  3.09it/s]

best params saved: val acc: 25.400% val loss: 1.3520


  1%|          | 118/10000 [00:38<53:24,  3.08it/s]

best params saved: val acc: 23.800% val loss: 1.3439


  1%|          | 119/10000 [00:38<53:23,  3.08it/s]

best params saved: val acc: 23.400% val loss: 1.3360


  1%|          | 120/10000 [00:38<53:26,  3.08it/s]

best params saved: val acc: 24.200% val loss: 1.3360


  1%|          | 121/10000 [00:39<53:30,  3.08it/s]

best params saved: val acc: 25.600% val loss: 1.3229


  1%|          | 122/10000 [00:39<53:43,  3.06it/s]

best params saved: val acc: 24.800% val loss: 1.3071


  1%|          | 123/10000 [00:40<53:55,  3.05it/s]

best params saved: val acc: 23.400% val loss: 1.3053


  1%|          | 124/10000 [00:40<53:57,  3.05it/s]

best params saved: val acc: 25.600% val loss: 1.2966


  1%|▏         | 125/10000 [00:40<53:58,  3.05it/s]

best params saved: val acc: 25.600% val loss: 1.2910


  1%|▏         | 126/10000 [00:41<54:09,  3.04it/s]

best params saved: val acc: 26.800% val loss: 1.2861


  1%|▏         | 127/10000 [00:41<54:23,  3.03it/s]

best params saved: val acc: 25.400% val loss: 1.2764


  1%|▏         | 128/10000 [00:42<54:41,  3.01it/s]

best params saved: val acc: 26.200% val loss: 1.2697


  1%|▏         | 129/10000 [00:43<54:54,  3.00it/s]

best params saved: val acc: 26.000% val loss: 1.2636


  1%|▏         | 130/10000 [00:43<55:07,  2.98it/s]

best params saved: val acc: 28.200% val loss: 1.2589


  1%|▏         | 131/10000 [00:44<55:16,  2.98it/s]

best params saved: val acc: 24.200% val loss: 1.2543


  1%|▏         | 132/10000 [00:44<55:21,  2.97it/s]

best params saved: val acc: 29.000% val loss: 1.2487


  1%|▏         | 133/10000 [00:44<55:22,  2.97it/s]

best params saved: val acc: 28.400% val loss: 1.2278


  1%|▏         | 134/10000 [00:45<55:23,  2.97it/s]

best params saved: val acc: 30.800% val loss: 1.2222


  1%|▏         | 135/10000 [00:45<55:34,  2.96it/s]

best params saved: val acc: 30.000% val loss: 1.2105


  1%|▏         | 136/10000 [00:46<55:38,  2.95it/s]

best params saved: val acc: 29.200% val loss: 1.2010


  1%|▏         | 137/10000 [00:46<55:45,  2.95it/s]

best params saved: val acc: 33.000% val loss: 1.1956


  1%|▏         | 138/10000 [00:46<55:44,  2.95it/s]

best params saved: val acc: 33.600% val loss: 1.1887


  1%|▏         | 139/10000 [00:47<55:45,  2.95it/s]

best params saved: val acc: 33.600% val loss: 1.1813


  1%|▏         | 140/10000 [00:47<55:47,  2.95it/s]

best params saved: val acc: 34.200% val loss: 1.1654


  1%|▏         | 141/10000 [00:47<55:47,  2.94it/s]

best params saved: val acc: 35.400% val loss: 1.1590


  1%|▏         | 142/10000 [00:48<55:50,  2.94it/s]

best params saved: val acc: 33.400% val loss: 1.1522


  1%|▏         | 143/10000 [00:48<55:51,  2.94it/s]

best params saved: val acc: 35.800% val loss: 1.1473


  1%|▏         | 144/10000 [00:48<55:49,  2.94it/s]

best params saved: val acc: 34.000% val loss: 1.1450


  1%|▏         | 145/10000 [00:49<55:55,  2.94it/s]

best params saved: val acc: 37.000% val loss: 1.1266


  1%|▏         | 146/10000 [00:49<56:01,  2.93it/s]

best params saved: val acc: 36.600% val loss: 1.1100


  1%|▏         | 147/10000 [00:50<56:07,  2.93it/s]

best params saved: val acc: 36.400% val loss: 1.1028


  1%|▏         | 148/10000 [00:50<56:07,  2.93it/s]

best params saved: val acc: 38.400% val loss: 1.0853


  1%|▏         | 149/10000 [00:50<56:07,  2.93it/s]

best params saved: val acc: 40.800% val loss: 1.0765


  2%|▏         | 150/10000 [00:51<56:12,  2.92it/s]

best params saved: val acc: 40.400% val loss: 1.0731


  2%|▏         | 151/10000 [00:51<56:14,  2.92it/s]

best params saved: val acc: 42.000% val loss: 1.0562


  2%|▏         | 152/10000 [00:52<56:18,  2.92it/s]

best params saved: val acc: 44.000% val loss: 1.0511


  2%|▏         | 153/10000 [00:52<56:19,  2.91it/s]

best params saved: val acc: 44.400% val loss: 1.0361


  2%|▏         | 154/10000 [00:52<56:21,  2.91it/s]

best params saved: val acc: 44.400% val loss: 1.0228


  2%|▏         | 155/10000 [00:53<56:34,  2.90it/s]

best params saved: val acc: 48.000% val loss: 1.0150


  2%|▏         | 156/10000 [00:53<56:44,  2.89it/s]

best params saved: val acc: 45.400% val loss: 1.0020


  2%|▏         | 157/10000 [00:54<56:49,  2.89it/s]

best params saved: val acc: 51.800% val loss: 0.9936


  2%|▏         | 158/10000 [00:54<56:47,  2.89it/s]

best params saved: val acc: 49.600% val loss: 0.9859


  2%|▏         | 159/10000 [00:55<56:45,  2.89it/s]

best params saved: val acc: 49.000% val loss: 0.9755


  2%|▏         | 160/10000 [00:55<56:48,  2.89it/s]

best params saved: val acc: 52.400% val loss: 0.9595


  2%|▏         | 162/10000 [00:56<56:52,  2.88it/s]

best params saved: val acc: 51.600% val loss: 0.9362


  2%|▏         | 163/10000 [00:56<56:51,  2.88it/s]

best params saved: val acc: 54.400% val loss: 0.9268


  2%|▏         | 164/10000 [00:56<56:52,  2.88it/s]

best params saved: val acc: 55.600% val loss: 0.9212


  2%|▏         | 165/10000 [00:57<57:00,  2.88it/s]

best params saved: val acc: 55.600% val loss: 0.9085


  2%|▏         | 166/10000 [00:57<57:12,  2.87it/s]

best params saved: val acc: 58.800% val loss: 0.8957


  2%|▏         | 167/10000 [00:58<57:13,  2.86it/s]

best params saved: val acc: 55.800% val loss: 0.8877


  2%|▏         | 168/10000 [00:58<57:12,  2.86it/s]

best params saved: val acc: 60.000% val loss: 0.8767


  2%|▏         | 169/10000 [00:59<57:13,  2.86it/s]

best params saved: val acc: 60.800% val loss: 0.8575


  2%|▏         | 170/10000 [00:59<57:17,  2.86it/s]

best params saved: val acc: 61.800% val loss: 0.8520


  2%|▏         | 171/10000 [00:59<57:19,  2.86it/s]

best params saved: val acc: 62.000% val loss: 0.8351


  2%|▏         | 172/10000 [01:00<57:23,  2.85it/s]

best params saved: val acc: 62.800% val loss: 0.8319


  2%|▏         | 173/10000 [01:00<57:22,  2.85it/s]

best params saved: val acc: 64.800% val loss: 0.8116


  2%|▏         | 174/10000 [01:00<57:19,  2.86it/s]

best params saved: val acc: 64.800% val loss: 0.7990


  2%|▏         | 176/10000 [01:01<57:21,  2.85it/s]

best params saved: val acc: 68.400% val loss: 0.7801


  2%|▏         | 177/10000 [01:02<57:23,  2.85it/s]

best params saved: val acc: 68.600% val loss: 0.7669


  2%|▏         | 178/10000 [01:02<57:26,  2.85it/s]

best params saved: val acc: 71.200% val loss: 0.7546


  2%|▏         | 179/10000 [01:02<57:25,  2.85it/s]

best params saved: val acc: 69.800% val loss: 0.7423


  2%|▏         | 180/10000 [01:03<57:26,  2.85it/s]

best params saved: val acc: 71.200% val loss: 0.7332


  2%|▏         | 181/10000 [01:03<57:28,  2.85it/s]

best params saved: val acc: 70.600% val loss: 0.7219


  2%|▏         | 182/10000 [01:03<57:29,  2.85it/s]

best params saved: val acc: 71.600% val loss: 0.7060


  2%|▏         | 183/10000 [01:04<57:31,  2.84it/s]

best params saved: val acc: 74.200% val loss: 0.6922


  2%|▏         | 184/10000 [01:04<57:30,  2.84it/s]

best params saved: val acc: 73.200% val loss: 0.6803


  2%|▏         | 185/10000 [01:05<57:28,  2.85it/s]

best params saved: val acc: 75.000% val loss: 0.6718


  2%|▏         | 186/10000 [01:05<57:32,  2.84it/s]

best params saved: val acc: 74.000% val loss: 0.6621


  2%|▏         | 187/10000 [01:05<57:35,  2.84it/s]

best params saved: val acc: 77.000% val loss: 0.6480


  2%|▏         | 188/10000 [01:06<57:36,  2.84it/s]

best params saved: val acc: 77.400% val loss: 0.6352


  2%|▏         | 189/10000 [01:06<57:36,  2.84it/s]

best params saved: val acc: 78.000% val loss: 0.6246


  2%|▏         | 190/10000 [01:06<57:33,  2.84it/s]

best params saved: val acc: 79.200% val loss: 0.6176


  2%|▏         | 191/10000 [01:07<57:38,  2.84it/s]

best params saved: val acc: 78.800% val loss: 0.6051


  2%|▏         | 192/10000 [01:07<57:38,  2.84it/s]

best params saved: val acc: 78.800% val loss: 0.5922


  2%|▏         | 193/10000 [01:08<57:43,  2.83it/s]

best params saved: val acc: 80.000% val loss: 0.5815


  2%|▏         | 194/10000 [01:08<57:42,  2.83it/s]

best params saved: val acc: 79.200% val loss: 0.5724


  2%|▏         | 195/10000 [01:08<57:39,  2.83it/s]

best params saved: val acc: 80.800% val loss: 0.5604


  2%|▏         | 196/10000 [01:09<57:39,  2.83it/s]

best params saved: val acc: 81.600% val loss: 0.5536


  2%|▏         | 197/10000 [01:09<57:39,  2.83it/s]

best params saved: val acc: 82.000% val loss: 0.5455


  2%|▏         | 198/10000 [01:09<57:39,  2.83it/s]

best params saved: val acc: 82.200% val loss: 0.5380


  2%|▏         | 199/10000 [01:10<57:38,  2.83it/s]

best params saved: val acc: 83.000% val loss: 0.5325


  2%|▏         | 200/10000 [01:10<57:36,  2.83it/s]

best params saved: val acc: 84.200% val loss: 0.5128


  2%|▏         | 201/10000 [01:10<57:33,  2.84it/s]

best params saved: val acc: 85.000% val loss: 0.5075


  2%|▏         | 202/10000 [01:11<57:40,  2.83it/s]

best params saved: val acc: 85.000% val loss: 0.4988


  2%|▏         | 203/10000 [01:11<57:49,  2.82it/s]

best params saved: val acc: 85.600% val loss: 0.4842


  2%|▏         | 204/10000 [01:12<57:53,  2.82it/s]

best params saved: val acc: 86.200% val loss: 0.4777


  2%|▏         | 206/10000 [01:13<57:56,  2.82it/s]

best params saved: val acc: 85.800% val loss: 0.4602


  2%|▏         | 207/10000 [01:13<57:59,  2.81it/s]

best params saved: val acc: 86.800% val loss: 0.4570


  2%|▏         | 208/10000 [01:13<58:03,  2.81it/s]

best params saved: val acc: 86.600% val loss: 0.4537


  2%|▏         | 209/10000 [01:14<58:05,  2.81it/s]

best params saved: val acc: 86.400% val loss: 0.4402


  2%|▏         | 210/10000 [01:14<58:03,  2.81it/s]

best params saved: val acc: 86.000% val loss: 0.4354


  2%|▏         | 211/10000 [01:15<58:04,  2.81it/s]

best params saved: val acc: 86.800% val loss: 0.4292


  2%|▏         | 212/10000 [01:15<58:06,  2.81it/s]

best params saved: val acc: 87.400% val loss: 0.4201


  2%|▏         | 213/10000 [01:15<58:07,  2.81it/s]

best params saved: val acc: 86.800% val loss: 0.4192


  2%|▏         | 214/10000 [01:16<58:11,  2.80it/s]

best params saved: val acc: 87.800% val loss: 0.4091


  2%|▏         | 215/10000 [01:16<58:11,  2.80it/s]

best params saved: val acc: 87.600% val loss: 0.4051


  2%|▏         | 216/10000 [01:17<58:13,  2.80it/s]

best params saved: val acc: 87.600% val loss: 0.4012


  2%|▏         | 217/10000 [01:17<58:18,  2.80it/s]

best params saved: val acc: 88.400% val loss: 0.3944


  2%|▏         | 218/10000 [01:17<58:19,  2.80it/s]

best params saved: val acc: 88.600% val loss: 0.3878


  2%|▏         | 219/10000 [01:18<58:23,  2.79it/s]

best params saved: val acc: 88.200% val loss: 0.3849


  2%|▏         | 220/10000 [01:18<58:21,  2.79it/s]

best params saved: val acc: 89.200% val loss: 0.3779


  2%|▏         | 221/10000 [01:19<58:21,  2.79it/s]

best params saved: val acc: 87.600% val loss: 0.3752


  2%|▏         | 222/10000 [01:19<58:23,  2.79it/s]

best params saved: val acc: 89.200% val loss: 0.3681


  2%|▏         | 223/10000 [01:19<58:25,  2.79it/s]

best params saved: val acc: 88.600% val loss: 0.3665


  2%|▏         | 224/10000 [01:20<58:25,  2.79it/s]

best params saved: val acc: 87.800% val loss: 0.3620


  2%|▏         | 225/10000 [01:20<58:24,  2.79it/s]

best params saved: val acc: 88.200% val loss: 0.3600


  2%|▏         | 226/10000 [01:21<58:24,  2.79it/s]

best params saved: val acc: 88.600% val loss: 0.3514


  2%|▏         | 227/10000 [01:21<58:25,  2.79it/s]

best params saved: val acc: 89.800% val loss: 0.3496


  2%|▏         | 228/10000 [01:21<58:26,  2.79it/s]

best params saved: val acc: 88.000% val loss: 0.3442


  2%|▏         | 230/10000 [01:22<58:28,  2.78it/s]

best params saved: val acc: 89.000% val loss: 0.3402


  2%|▏         | 231/10000 [01:22<58:28,  2.78it/s]

best params saved: val acc: 88.800% val loss: 0.3359


  2%|▏         | 232/10000 [01:23<58:30,  2.78it/s]

best params saved: val acc: 89.400% val loss: 0.3307


  2%|▏         | 233/10000 [01:23<58:32,  2.78it/s]

best params saved: val acc: 89.400% val loss: 0.3258


  2%|▏         | 234/10000 [01:24<58:33,  2.78it/s]

best params saved: val acc: 89.400% val loss: 0.3254


  2%|▏         | 235/10000 [01:24<58:34,  2.78it/s]

best params saved: val acc: 89.400% val loss: 0.3216


  2%|▏         | 236/10000 [01:24<58:31,  2.78it/s]

best params saved: val acc: 89.200% val loss: 0.3161


  2%|▏         | 237/10000 [01:25<58:31,  2.78it/s]

best params saved: val acc: 89.600% val loss: 0.3145


  2%|▏         | 239/10000 [01:26<58:32,  2.78it/s]

best params saved: val acc: 89.200% val loss: 0.3085


  2%|▏         | 240/10000 [01:26<58:33,  2.78it/s]

best params saved: val acc: 90.000% val loss: 0.3067


  2%|▏         | 241/10000 [01:26<58:31,  2.78it/s]

best params saved: val acc: 90.000% val loss: 0.3063


  2%|▏         | 242/10000 [01:27<58:29,  2.78it/s]

best params saved: val acc: 89.800% val loss: 0.3014


  2%|▏         | 244/10000 [01:27<58:30,  2.78it/s]

best params saved: val acc: 89.400% val loss: 0.2935


  2%|▏         | 246/10000 [01:28<58:29,  2.78it/s]

best params saved: val acc: 88.800% val loss: 0.2905


  2%|▏         | 247/10000 [01:28<58:27,  2.78it/s]

best params saved: val acc: 90.000% val loss: 0.2873


  2%|▏         | 248/10000 [01:29<58:28,  2.78it/s]

best params saved: val acc: 90.200% val loss: 0.2836


  2%|▎         | 250/10000 [01:30<58:32,  2.78it/s]

best params saved: val acc: 90.800% val loss: 0.2806


  3%|▎         | 251/10000 [01:30<58:31,  2.78it/s]

best params saved: val acc: 90.600% val loss: 0.2804


  3%|▎         | 253/10000 [01:31<58:27,  2.78it/s]

best params saved: val acc: 90.000% val loss: 0.2721


  3%|▎         | 255/10000 [01:31<58:33,  2.77it/s]

best params saved: val acc: 90.800% val loss: 0.2711


  3%|▎         | 256/10000 [01:32<58:36,  2.77it/s]

best params saved: val acc: 90.400% val loss: 0.2669


  3%|▎         | 257/10000 [01:32<58:37,  2.77it/s]

best params saved: val acc: 90.000% val loss: 0.2666


  3%|▎         | 258/10000 [01:33<58:36,  2.77it/s]

best params saved: val acc: 89.800% val loss: 0.2630


  3%|▎         | 260/10000 [01:34<58:45,  2.76it/s]

best params saved: val acc: 90.200% val loss: 0.2585


  3%|▎         | 261/10000 [01:34<58:44,  2.76it/s]

best params saved: val acc: 90.400% val loss: 0.2578


  3%|▎         | 262/10000 [01:34<58:41,  2.76it/s]

best params saved: val acc: 91.200% val loss: 0.2543


  3%|▎         | 263/10000 [01:35<58:42,  2.76it/s]

best params saved: val acc: 91.600% val loss: 0.2533


  3%|▎         | 264/10000 [01:35<58:45,  2.76it/s]

best params saved: val acc: 90.600% val loss: 0.2505


  3%|▎         | 266/10000 [01:36<58:48,  2.76it/s]

best params saved: val acc: 90.800% val loss: 0.2457


  3%|▎         | 269/10000 [01:37<58:50,  2.76it/s]

best params saved: val acc: 91.000% val loss: 0.2398


  3%|▎         | 271/10000 [01:38<58:52,  2.75it/s]

best params saved: val acc: 90.600% val loss: 0.2371


  3%|▎         | 272/10000 [01:38<58:49,  2.76it/s]

best params saved: val acc: 91.200% val loss: 0.2333


  3%|▎         | 274/10000 [01:39<58:48,  2.76it/s]

best params saved: val acc: 92.000% val loss: 0.2312


  3%|▎         | 276/10000 [01:40<58:50,  2.75it/s]

best params saved: val acc: 91.200% val loss: 0.2278


  3%|▎         | 278/10000 [01:40<58:48,  2.76it/s]

best params saved: val acc: 91.400% val loss: 0.2246


  3%|▎         | 279/10000 [01:41<58:49,  2.75it/s]

best params saved: val acc: 91.600% val loss: 0.2230


  3%|▎         | 280/10000 [01:41<58:50,  2.75it/s]

best params saved: val acc: 91.600% val loss: 0.2209


  3%|▎         | 281/10000 [01:42<58:53,  2.75it/s]

best params saved: val acc: 91.600% val loss: 0.2183


  3%|▎         | 282/10000 [01:42<58:55,  2.75it/s]

best params saved: val acc: 91.800% val loss: 0.2167


  3%|▎         | 283/10000 [01:42<58:53,  2.75it/s]

best params saved: val acc: 92.400% val loss: 0.2134


  3%|▎         | 286/10000 [01:44<58:55,  2.75it/s]

best params saved: val acc: 92.000% val loss: 0.2092


  3%|▎         | 288/10000 [01:44<58:54,  2.75it/s]

best params saved: val acc: 92.000% val loss: 0.2082


  3%|▎         | 289/10000 [01:45<58:55,  2.75it/s]

best params saved: val acc: 91.600% val loss: 0.2041


  3%|▎         | 291/10000 [01:46<58:59,  2.74it/s]

best params saved: val acc: 92.600% val loss: 0.2036


  3%|▎         | 292/10000 [01:46<59:00,  2.74it/s]

best params saved: val acc: 92.200% val loss: 0.2000


  3%|▎         | 294/10000 [01:47<58:56,  2.74it/s]

best params saved: val acc: 92.600% val loss: 0.1963


  3%|▎         | 295/10000 [01:47<58:56,  2.74it/s]

best params saved: val acc: 92.000% val loss: 0.1951


  3%|▎         | 299/10000 [01:48<58:51,  2.75it/s]

best params saved: val acc: 93.000% val loss: 0.1935


  3%|▎         | 300/10000 [01:49<58:50,  2.75it/s]

best params saved: val acc: 92.800% val loss: 0.1877


  3%|▎         | 302/10000 [01:50<58:52,  2.75it/s]

best params saved: val acc: 93.200% val loss: 0.1853


  3%|▎         | 303/10000 [01:50<58:55,  2.74it/s]

best params saved: val acc: 93.000% val loss: 0.1844


  3%|▎         | 304/10000 [01:50<58:54,  2.74it/s]

best params saved: val acc: 93.200% val loss: 0.1818


  3%|▎         | 306/10000 [01:51<58:55,  2.74it/s]

best params saved: val acc: 93.000% val loss: 0.1810


  3%|▎         | 307/10000 [01:52<58:57,  2.74it/s]

best params saved: val acc: 93.200% val loss: 0.1761


  3%|▎         | 308/10000 [01:52<58:57,  2.74it/s]

best params saved: val acc: 93.600% val loss: 0.1740


  3%|▎         | 311/10000 [01:53<58:55,  2.74it/s]

best params saved: val acc: 94.000% val loss: 0.1737


  3%|▎         | 312/10000 [01:54<59:00,  2.74it/s]

best params saved: val acc: 93.600% val loss: 0.1715


  3%|▎         | 313/10000 [01:54<58:59,  2.74it/s]

best params saved: val acc: 94.200% val loss: 0.1698


  3%|▎         | 314/10000 [01:54<58:59,  2.74it/s]

best params saved: val acc: 93.800% val loss: 0.1677


  3%|▎         | 315/10000 [01:55<58:58,  2.74it/s]

best params saved: val acc: 93.800% val loss: 0.1651


  3%|▎         | 318/10000 [01:56<59:02,  2.73it/s]

best params saved: val acc: 94.200% val loss: 0.1637


  3%|▎         | 320/10000 [01:57<58:59,  2.73it/s]

best params saved: val acc: 94.800% val loss: 0.1598


  3%|▎         | 322/10000 [01:57<58:59,  2.73it/s]

best params saved: val acc: 94.200% val loss: 0.1558


  3%|▎         | 324/10000 [01:58<58:58,  2.73it/s]

best params saved: val acc: 95.000% val loss: 0.1538


  3%|▎         | 325/10000 [01:58<58:56,  2.74it/s]

best params saved: val acc: 94.600% val loss: 0.1529


  3%|▎         | 327/10000 [01:59<58:54,  2.74it/s]

best params saved: val acc: 95.000% val loss: 0.1523


  3%|▎         | 329/10000 [02:00<58:53,  2.74it/s]

best params saved: val acc: 95.000% val loss: 0.1463


  3%|▎         | 332/10000 [02:01<58:50,  2.74it/s]

best params saved: val acc: 94.800% val loss: 0.1404


  3%|▎         | 335/10000 [02:02<58:53,  2.74it/s]

best params saved: val acc: 95.000% val loss: 0.1388


  3%|▎         | 340/10000 [02:04<58:51,  2.74it/s]

best params saved: val acc: 95.600% val loss: 0.1359


  3%|▎         | 341/10000 [02:04<58:49,  2.74it/s]

best params saved: val acc: 96.000% val loss: 0.1344


  3%|▎         | 343/10000 [02:05<58:48,  2.74it/s]

best params saved: val acc: 95.600% val loss: 0.1322


  3%|▎         | 345/10000 [02:06<58:50,  2.73it/s]

best params saved: val acc: 95.000% val loss: 0.1303


  3%|▎         | 346/10000 [02:06<58:50,  2.73it/s]

best params saved: val acc: 95.800% val loss: 0.1277


  3%|▎         | 349/10000 [02:07<58:48,  2.74it/s]

best params saved: val acc: 95.400% val loss: 0.1276


  4%|▎         | 350/10000 [02:07<58:49,  2.73it/s]

best params saved: val acc: 95.400% val loss: 0.1256


  4%|▎         | 352/10000 [02:08<58:48,  2.73it/s]

best params saved: val acc: 95.400% val loss: 0.1241


  4%|▎         | 353/10000 [02:09<58:47,  2.73it/s]

best params saved: val acc: 96.400% val loss: 0.1208


  4%|▎         | 356/10000 [02:10<58:47,  2.73it/s]

best params saved: val acc: 96.000% val loss: 0.1164


  4%|▎         | 357/10000 [02:10<58:46,  2.73it/s]

best params saved: val acc: 96.200% val loss: 0.1159


  4%|▎         | 359/10000 [02:11<58:44,  2.74it/s]

best params saved: val acc: 96.000% val loss: 0.1141


  4%|▎         | 363/10000 [02:12<58:46,  2.73it/s]

best params saved: val acc: 96.800% val loss: 0.1136


  4%|▎         | 365/10000 [02:13<58:44,  2.73it/s]

best params saved: val acc: 96.600% val loss: 0.1102


  4%|▎         | 366/10000 [02:13<58:45,  2.73it/s]

best params saved: val acc: 96.400% val loss: 0.1084


  4%|▎         | 369/10000 [02:14<58:42,  2.73it/s]

best params saved: val acc: 96.800% val loss: 0.1076


  4%|▎         | 370/10000 [02:15<58:41,  2.73it/s]

best params saved: val acc: 96.600% val loss: 0.1062


  4%|▎         | 371/10000 [02:15<58:41,  2.73it/s]

best params saved: val acc: 96.200% val loss: 0.1020


  4%|▍         | 375/10000 [02:17<58:40,  2.73it/s]

best params saved: val acc: 96.600% val loss: 0.1015


  4%|▍         | 376/10000 [02:17<58:41,  2.73it/s]

best params saved: val acc: 96.800% val loss: 0.1010


  4%|▍         | 377/10000 [02:17<58:42,  2.73it/s]

best params saved: val acc: 96.800% val loss: 0.0999


  4%|▍         | 379/10000 [02:18<58:40,  2.73it/s]

best params saved: val acc: 96.800% val loss: 0.0995


  4%|▍         | 380/10000 [02:19<58:39,  2.73it/s]

best params saved: val acc: 97.000% val loss: 0.0995


  4%|▍         | 382/10000 [02:19<58:37,  2.73it/s]

best params saved: val acc: 97.200% val loss: 0.0981


  4%|▍         | 383/10000 [02:20<58:37,  2.73it/s]

best params saved: val acc: 97.000% val loss: 0.0939


  4%|▍         | 385/10000 [02:20<58:34,  2.74it/s]

best params saved: val acc: 97.000% val loss: 0.0938


  4%|▍         | 386/10000 [02:21<58:33,  2.74it/s]

best params saved: val acc: 97.000% val loss: 0.0920


  4%|▍         | 395/10000 [02:24<58:33,  2.73it/s]

best params saved: val acc: 97.000% val loss: 0.0903


  4%|▍         | 396/10000 [02:24<58:32,  2.73it/s]

best params saved: val acc: 97.000% val loss: 0.0892


  4%|▍         | 399/10000 [02:26<58:37,  2.73it/s]

best params saved: val acc: 97.400% val loss: 0.0880


  4%|▍         | 400/10000 [02:26<58:36,  2.73it/s]

best params saved: val acc: 97.000% val loss: 0.0831


  4%|▍         | 407/10000 [02:28<58:31,  2.73it/s]

best params saved: val acc: 97.400% val loss: 0.0827


  4%|▍         | 408/10000 [02:29<58:31,  2.73it/s]

best params saved: val acc: 97.600% val loss: 0.0820


  4%|▍         | 409/10000 [02:29<58:31,  2.73it/s]

best params saved: val acc: 97.400% val loss: 0.0819


  4%|▍         | 410/10000 [02:30<58:34,  2.73it/s]

best params saved: val acc: 97.200% val loss: 0.0816


  4%|▍         | 412/10000 [02:31<58:40,  2.72it/s]

best params saved: val acc: 97.600% val loss: 0.0795


  4%|▍         | 413/10000 [02:31<58:48,  2.72it/s]

best params saved: val acc: 97.200% val loss: 0.0790


  4%|▍         | 414/10000 [02:32<58:51,  2.71it/s]

best params saved: val acc: 97.200% val loss: 0.0759


  4%|▍         | 415/10000 [02:33<58:54,  2.71it/s]

best params saved: val acc: 97.400% val loss: 0.0743


  4%|▍         | 427/10000 [02:37<58:54,  2.71it/s]

best params saved: val acc: 97.400% val loss: 0.0718


  4%|▍         | 428/10000 [02:38<58:53,  2.71it/s]

best params saved: val acc: 97.200% val loss: 0.0690


  4%|▍         | 429/10000 [02:38<58:51,  2.71it/s]

best params saved: val acc: 97.600% val loss: 0.0686


  4%|▍         | 438/10000 [02:41<58:47,  2.71it/s]

best params saved: val acc: 97.800% val loss: 0.0671


  4%|▍         | 439/10000 [02:42<58:48,  2.71it/s]

best params saved: val acc: 97.400% val loss: 0.0647


  4%|▍         | 442/10000 [02:43<58:54,  2.70it/s]

best params saved: val acc: 97.600% val loss: 0.0621


  4%|▍         | 449/10000 [02:46<58:54,  2.70it/s]

best params saved: val acc: 98.200% val loss: 0.0616


  5%|▍         | 454/10000 [02:48<58:53,  2.70it/s]

best params saved: val acc: 97.800% val loss: 0.0612


  5%|▍         | 456/10000 [02:48<58:53,  2.70it/s]

best params saved: val acc: 98.400% val loss: 0.0605


  5%|▍         | 458/10000 [02:49<58:55,  2.70it/s]

best params saved: val acc: 98.000% val loss: 0.0582


  5%|▍         | 467/10000 [02:52<58:48,  2.70it/s]

best params saved: val acc: 98.400% val loss: 0.0572


  5%|▍         | 468/10000 [02:53<58:49,  2.70it/s]

best params saved: val acc: 98.400% val loss: 0.0558


  5%|▍         | 474/10000 [02:55<58:49,  2.70it/s]

best params saved: val acc: 98.000% val loss: 0.0549


  5%|▍         | 475/10000 [02:56<58:50,  2.70it/s]

best params saved: val acc: 98.600% val loss: 0.0537


  5%|▍         | 478/10000 [02:57<58:48,  2.70it/s]

best params saved: val acc: 98.600% val loss: 0.0532


  5%|▍         | 485/10000 [02:59<58:48,  2.70it/s]

best params saved: val acc: 98.800% val loss: 0.0515


  5%|▍         | 495/10000 [03:03<58:47,  2.69it/s]

best params saved: val acc: 98.800% val loss: 0.0489


  5%|▍         | 499/10000 [03:05<58:49,  2.69it/s]

best params saved: val acc: 98.600% val loss: 0.0475


  5%|▌         | 504/10000 [03:07<58:50,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0453


  5%|▌         | 511/10000 [03:09<58:45,  2.69it/s]

best params saved: val acc: 99.000% val loss: 0.0451


  5%|▌         | 527/10000 [03:15<58:31,  2.70it/s]

best params saved: val acc: 98.800% val loss: 0.0419


  5%|▌         | 541/10000 [03:20<58:32,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0418


  5%|▌         | 543/10000 [03:21<58:31,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0417


  5%|▌         | 548/10000 [03:23<58:30,  2.69it/s]

best params saved: val acc: 99.000% val loss: 0.0409


  6%|▌         | 552/10000 [03:24<58:28,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0409


  6%|▌         | 553/10000 [03:25<58:28,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0400


  6%|▌         | 566/10000 [03:30<58:26,  2.69it/s]

best params saved: val acc: 99.000% val loss: 0.0397


  6%|▌         | 577/10000 [03:34<58:20,  2.69it/s]

best params saved: val acc: 99.000% val loss: 0.0391


  6%|▌         | 578/10000 [03:34<58:19,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0382


  6%|▌         | 581/10000 [03:35<58:19,  2.69it/s]

best params saved: val acc: 99.200% val loss: 0.0345


  6%|▌         | 601/10000 [03:43<58:08,  2.69it/s]

best params saved: val acc: 99.000% val loss: 0.0341


  6%|▌         | 611/10000 [03:46<58:01,  2.70it/s]

best params saved: val acc: 99.200% val loss: 0.0336


  6%|▌         | 616/10000 [03:48<57:59,  2.70it/s]

best params saved: val acc: 99.400% val loss: 0.0311


  6%|▋         | 641/10000 [03:56<57:31,  2.71it/s]

best params saved: val acc: 99.400% val loss: 0.0295


  7%|▋         | 655/10000 [04:01<57:19,  2.72it/s]

best params saved: val acc: 99.400% val loss: 0.0284


  7%|▋         | 666/10000 [04:04<57:10,  2.72it/s]

best params saved: val acc: 99.400% val loss: 0.0274


  7%|▋         | 733/10000 [04:26<56:10,  2.75it/s]

KeyboardInterrupt: 

In [242]:
reset_graph()
hypms = create_hyper_params()
g_eval = build_graph()
best_params = load_obj(BEST_PARAMS_PATH)
pred_dict = {}
with tf.Session(graph=g_eval) as sess:
    saver, init_global, init_local = g_eval.get_collection("save_init")
    X, y, training_op = g_eval.get_collection("main_ops")
    Y_proba, y_true_cls, y_pred_cls, _ = g_eval.get_collection("preds")
    test_auc, test_auc_update, test_acc, test_acc_update, test_acc_reset_op = g_eval.get_collection("test_metrics")
    test_mean_loss, test_mean_loss_update, test_loss_reset_op = g_eval.get_collection("test_loss")
    
    restore_model_params(model_params=best_params, g=g_eval, sess=sess)
    sess.run([test_acc_reset_op, test_loss_reset_op])

    # run test
    low_i = 0
    high_i = 0
    for iteration in range(len(X_test) // hypms['batch_size']):
        low_i = iteration*hypms['batch_size']
        high_i = (iteration+1)*hypms['batch_size']
        Xtb = X_test[low_i:high_i]     
        ytb = y_test[low_i:high_i]
        sess.run([test_auc_update, test_acc_update, test_mean_loss_update], 
                     feed_dict={X:Xtb, y:ytb})
        cur_preds = sess.run(Y_proba, feed_dict={X: Xtb, y: ytb})
        print(cur_preds)
        for i, v in enumerate(Xtb):
            pred_dict[binary_decode(v)] = fizz_buzz_decode(cur_preds[i])
    
    Xtb = X_test[high_i:]
    ytb = y_test[high_i:]
    if len(Xtb) > 0:
        sess.run([test_auc_update, test_acc_update, test_mean_loss_update], 
                 feed_dict={X: Xtb, y: ytb})
        cur_preds = sess.run(Y_proba, feed_dict={X: Xtb, y: ytb})
        print(cur_preds)
        for i, v in enumerate(Xtb):
            pred_dict[binary_decode(v)] = ind_class_decode(np.argmax(cur_preds[i]))
        
    # print
    final_test_acc, final_test_loss, final_test_auc = sess.run([test_acc, test_mean_loss, test_auc])
    print("test auc: {:.3f}% acc: {:.3f}% loss: {:.5f}".format(final_test_auc*100, 
                                                              final_test_acc*100,
                                                              final_test_loss))

Tensor("model/output/Y_proba:0", shape=(?, 4), dtype=float32)
[[  8.86257112e-01   5.05328132e-03   7.79468985e-03   1.00894980e-01]
 [  2.91699320e-01   6.77601218e-01   3.06994542e-02   9.41671914e-08]
 [  2.10215494e-01   2.08207339e-01   5.81576645e-01   5.53621078e-07]
 [  8.66933726e-04   3.84739451e-06   9.99129236e-01   1.54160545e-10]
 [  4.14531864e-02   9.40195322e-01   1.83513947e-02   1.18437733e-07]
 [  1.30701255e-05   9.99234200e-01   7.52765685e-04   2.01820743e-12]
 [  7.98468664e-03   9.58644506e-03   9.82428849e-01   4.88147087e-08]
 [  9.99857306e-01   2.89295494e-05   1.07260930e-04   6.48994273e-06]
 [  9.97536302e-01   2.42313463e-03   3.57183890e-05   4.87980924e-06]
 [  1.93903354e-04   2.36115558e-03   9.97444868e-01   1.32860570e-10]
 [  2.85350216e-05   9.99517560e-01   4.53910558e-04   4.19703694e-09]
 [  9.99856710e-01   1.33093868e-04   1.00954394e-05   1.17483818e-08]
 [  2.86269846e-04   1.74742854e-05   9.99696255e-01   1.69794144e-11]
 [  9.99874353e

In [243]:
for k in pred_dict:
    print(k,pred_dict[k])

0 None
1 Fizz
2 Buzz
3 Buzz
4 Fizz
5 Fizz
6 Buzz
7 None
8 None
9 Buzz
10 Fizz
11 None
12 Buzz
13 None
14 None
15 FizzBuzz
16 Buzz
17 Buzz
18 Buzz
19 None
20 Fizz
21 Buzz
22 None
23 None
24 Buzz
25 Fizz
26 None
27 Buzz
28 None
29 None
30 FizzBuzz
31 None
32 Buzz
33 Buzz
34 Buzz
35 Fizz
36 Buzz
37 None
38 None
39 Buzz
40 Fizz
41 None
42 Buzz
43 None
44 None
45 FizzBuzz
46 None
47 None
48 Buzz
49 None
50 Fizz
51 Buzz
52 None
53 None
54 Buzz
55 Fizz
56 None
57 Buzz
58 None
59 None
60 FizzBuzz
61 None
62 None
63 Buzz
64 Fizz
65 Fizz
66 Buzz
67 None
68 Buzz
69 Buzz
70 Fizz
71 None
72 Buzz
73 None
74 None
75 FizzBuzz
76 None
77 None
78 Buzz
79 None
80 Fizz
81 Buzz
82 None
83 None
84 Buzz
85 Fizz
86 None
87 Buzz
88 None
89 None
90 FizzBuzz
91 None
92 None
93 Buzz
94 None
95 Fizz
96 Buzz
97 None
98 None
99 Buzz
