In [1]:
import sys
import numpy as np

print("Python: {}".format(sys.version_info[:]))
print('Numpy: {}'.format(np.__version__))

Python: (3, 6, 3, 'final', 0)
Numpy: 1.13.3


## Basics

In [2]:
# example of array
# note the use of `[]`
np_example = np.array([10,11,12,13,14,15,16,17,18,19,20])

# this will throw an error
# np_example = np.array(1,2,3,4)

In [3]:
# viewing information about the object
print("np_example = {}".format(np_example))
print("np_example.shape = {}".format(np_example.shape))
print("np_example.dtype = {}".format(np_example.dtype))

np_example = [10 11 12 13 14 15 16 17 18 19 20]
np_example.shape = (11,)
np_example.dtype = int64


In [4]:
# indexing objects in the array
print("np_example[3] = {}".format(np_example[3]))
print("np_example[-1] = {}".format(np_example[-1]))
#
print("\nnp_example[:] = {}".format(np_example[:]))
print("np_example[:3] = {}".format(np_example[:3]))
print("np_example[3:] = {}".format(np_example[3:]))
#
print("\nnp_example[::2] = {}".format(np_example[::2]))
print("np_example[::-1] = {}".format(np_example[::-1]))
print("np_example[::-3] = {}".format(np_example[::-3]))

np_example[3] = 13
np_example[-1] = 20

np_example[:] = [10 11 12 13 14 15 16 17 18 19 20]
np_example[:3] = [10 11 12]
np_example[3:] = [13 14 15 16 17 18 19 20]

np_example[::2] = [10 12 14 16 18 20]
np_example[::-1] = [20 19 18 17 16 15 14 13 12 11 10]
np_example[::-3] = [20 17 14 11]


In [9]:
# using dtype to specifiy the type
np_example = np.array([10,11,12,13,14,15,16,17,18,19,20], dtype=np.float64)
print("np_example.dtype = {}".format(np_example.dtype))

# what will it do by default if they're all floats?
np_example = np.array([10.,11.,12.,13.,14.,15.,16.,17.,18.,19.,20.])
print("np_example.dtype = {}".format(np_example.dtype))

# what will it do by default if just one is specified as a float?
np_example = np.array([10,11.,12,13,14,15,16,17,18,19,20])
print("np_example.dtype = {}".format(np_example.dtype))

np_example.dtype = float64
np_example.dtype = float64
np_example.dtype = float64


### Types
Common types. Most common in **bold**. [Relevent documentation](https://docs.scipy.org/doc/numpy/user/basics.types.html)

Boolean

- **`bool`**

Signed Int

- `int8` _(-128, 127)_
- `int16` _(-32768, 32767)_
- `int32`  _(-2147483648, 2147483647)_
- **`int64`** _(-9223372036854775808, 9223372036854775807)_

Unsigned Int

- `uint8` _(0, 255)_
- `uint16` _(0, 65535)_
- `uint32`  _(0, 4294967295)_
- `uint64` _(0, 18446744073709551615)_

Floats

- `float16` "half precision"
- `float32` "Single precision"
- **`float64`** "Double precision"

## special initializations

In [27]:
# zeros

# initialize by `shape` keyword
np_example = np.zeros(shape=(3,6))
print("np_example = \n{}".format(np_example))
print("np_example.shape = {}".format(np_example.shape))
print("np_example.dtype = {}".format(np_example.dtype))

# if we don't use the keyword, this will still work
np_example = np.zeros((3,6))
print("np_example = \n{}".format(np_example))
print("np_example.shape = {}".format(np_example.shape))
print("np_example.dtype = {}".format(np_example.dtype))

np_example = 
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
np_example.shape = (3, 6)
np_example.dtype = float64
np_example = 
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
np_example.shape = (3, 6)
np_example.dtype = float64


In [16]:
# ones
np_example = np.ones((3,6))
print("np_example = \n{}".format(np_example))
print("np_example.shape = {}".format(np_example.shape))
print("np_example.dtype = {}".format(np_example.dtype))

np_example = 
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
np_example.shape = (3, 6)
np_example.dtype = float64


In [23]:
# empty
# > output will vary
np_example = np.empty((2,2))
print("np_example = \n{}".format(np_example))
print("np_example.shape = {}".format(np_example.shape))
print("np_example.dtype = {}".format(np_example.dtype))

np_example = 
[[  9.88131292e-323   8.39911598e-323]
 [  6.91691904e-323   5.43472210e-323]]
np_example.shape = (2, 2)
np_example.dtype = float64


## Reshape

In [34]:
# 1D vs 2D vs 3D
# this will create a 1D array in the range [0,value)
vals_1D = np.arange(27)
print("vals_1D = \n{}".format(vals_1D))
print("vals_1D.shape = {}".format(vals_1D.shape))

vals_2D = vals_1D.reshape(9,3)
print("\nvals_2D = \n{}".format(vals_2D))
print("vals_2D.shape = {}".format(vals_2D.shape))

vals_2D = vals_1D.reshape(3,9)
print("\nvals_2D = \n{}".format(vals_2D))
print("vals_2D.shape = {}".format(vals_2D.shape))

vals_3D = vals_1D.reshape(3,3,3)
print("\nvals_3D = \n{}".format(vals_3D))
print("vals_3D.shape = {}".format(vals_3D.shape))

vals_1D = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]
vals_1D.shape = (27,)

vals_2D = 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]
vals_2D.shape = (9, 3)

vals_2D = 
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
vals_2D.shape = (3, 9)

vals_3D = 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
vals_3D.shape = (3, 3, 3)


In [ ]:
## Convert list to numpy array