# Numpy Arithmetic

Examples of how to perform basic arithmetic with numpy.  Several of the most common functions, specific to this domain, are shown below.  If you wish to see even more functions and examples please refer to the [documentation](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

## Overview
- Subtraction
- Addition
- Multiplication
- Dot
- Division
- Exponent
- Transpose


## To be aware of
> when operating on different types, the resulting type will be the more general or more precise type (upcasting)



**Note**: Please see [numpy_initialization_and_viewing.ipynb](./numpy_initialization_and_viewing.ipynb) for an introduction to numpy as well as links for numpy documentation

In [1]:
import sys
import numpy as np

print("Python: {}".format(sys.version_info[:]))
print('Numpy: {}'.format(np.__version__))

Python: (3, 6, 3, 'final', 0)
Numpy: 1.13.3


In [2]:
np_a = np.arange(9).reshape(3,3)
np_b = np.arange(90,99).reshape(3,3)

print("np_a; \n{}".format(np_a))
print("np_a.shape = {}, np_a.dtype = {}".format(np_a.shape, np_a.dtype))

print("\nnp_b; \n{}".format(np_b))
print("np_b.shape = {}, np_b.dtype = {}".format(np_b.shape, np_b.dtype))

np_a; 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
np_a.shape = (3, 3), np_a.dtype = int64

np_b; 
[[90 91 92]
 [93 94 95]
 [96 97 98]]
np_b.shape = (3, 3), np_b.dtype = int64


## Subtraction

In [3]:
# using np.subtract()
np_sub = np.subtract(np_b, np_a)
print("np_sub (np.subract(np_b, np_a)); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

# using `-` operator
np_sub = np_b - np_a
print("\nnp_sub (np_b - np_a); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

np_sub (np.subract(np_b, np_a)); 
[[90 90 90]
 [90 90 90]
 [90 90 90]]
np_sub.shape = (3, 3), np_sub.dtype = int64

np_sub (np_b - np_a); 
[[90 90 90]
 [90 90 90]
 [90 90 90]]
np_sub.shape = (3, 3), np_sub.dtype = int64


In [4]:
np_sub = np_b - 10
print("\nnp_sub (np_b - 10); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))


np_sub (np_b - 10); 
[[80 81 82]
 [83 84 85]
 [86 87 88]]
np_sub.shape = (3, 3), np_sub.dtype = int64


### NOTE: Type conversion

In [5]:
# NOTE THE CHANGE TO FLOAT!
np_sub = np_b - 10.
print("np_sub (np_b - 10.); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

np_sub (np_b - 10.); 
[[ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]]
np_sub.shape = (3, 3), np_sub.dtype = float64


In [6]:
np_b_32 = np.arange(90,99).reshape(3,3).astype(np.int32)
print("np_b_32; \n{}".format(np_b_32))
print("np_b_32.shape = {}, np_b_32.dtype = {}".format(np_b_32.shape, np_b_32.dtype))

np_b_32; 
[[90 91 92]
 [93 94 95]
 [96 97 98]]
np_b_32.shape = (3, 3), np_b_32.dtype = int32


In [7]:
# note the change back up to int64
np_sub = np_b_32 - np_a
print("np_sub (np_b_32 - np_a); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

np_sub (np_b_32 - np_a); 
[[90 90 90]
 [90 90 90]
 [90 90 90]]
np_sub.shape = (3, 3), np_sub.dtype = int64


In [8]:
# this should be expected by now
np_sub = np_b_32 - 10.
print("np_sub (np_b_32 - 10.); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

np_sub (np_b_32 - 10.); 
[[ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]]
np_sub.shape = (3, 3), np_sub.dtype = float64


In [9]:
# note: will go straight to float64
ten_float32 = np.float32(10)
print("np_b_32.dtype = {}, ten_float32.dtype = {}".format(np_b_32.dtype, ten_float32.dtype))

np_sub = np_b_32 - ten_float32
print("np_sub (np_b - ten_float32); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

np_b_32.dtype = int32, ten_float32.dtype = float32
np_sub (np_b - ten_float32); 
[[ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]]
np_sub.shape = (3, 3), np_sub.dtype = float64


### Bottom line:
99% of the time, these conversions won't be an issue. It is just something to be aware of.  **This may arrise as an inssue when you are feeding placeholder tensors with numpy data** (ask me how I know...)

## Addition

In [10]:
np_add = np_b + np_a
print("np_add (np_b + np_a); \n{}".format(np_add))
print("np_add.shape = {}, np_add.dtype = {}".format(np_add.shape, np_add.dtype))

np_add (np_b + np_a); 
[[ 90  92  94]
 [ 96  98 100]
 [102 104 106]]
np_add.shape = (3, 3), np_add.dtype = int64


In [11]:
np_add = np_a + np.asarray([10,20,30])
print("np_add (np_a + np.asarray([10,20,30])); \n{}".format(np_add))
print("np_add.shape = {}, np_add.dtype = {}".format(np_add.shape, np_add.dtype))

np_add (np_a + np.asarray([10,20,30])); 
[[10 21 32]
 [13 24 35]
 [16 27 38]]
np_add.shape = (3, 3), np_add.dtype = int64


## Multiplication

In [12]:
# note; the `*` operator operates elementwise 
# - please see np.dot() example below for dot product
np_mult = np_a * 10
print("np_mult (np_a * 10); \n{}".format(np_mult))
print("np_mult.shape = {}, np_mult.dtype = {}".format(np_mult.shape, np_mult.dtype))

np_mult (np_a * 10); 
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
np_mult.shape = (3, 3), np_mult.dtype = int64


In [13]:
np_mult = np_a * np.asarray([10,20,30])
print("np_mult (np_a * np.asarray([10,20,30])); \n{}".format(np_mult))
print("np_mult.shape = {}, np_mult.dtype = {}".format(np_mult.shape, np_mult.dtype))

np_mult (np_a * np.asarray([10,20,30])); 
[[  0  20  60]
 [ 30  80 150]
 [ 60 140 240]]
np_mult.shape = (3, 3), np_mult.dtype = int64


In [14]:
np_mult = np.multiply(np_b, np_a)
print("np_mult (np.multiply(np_b, np_a)); \n{}".format(np_mult))
print("np_mult.shape = {}, np_mult.dtype = {}".format(np_mult.shape, np_mult.dtype))

np_mult = np_b * np_a
print("\nnp_mult (np_b * np_a); \n{}".format(np_mult))
print("np_mult.shape = {}, np_mult.dtype = {}".format(np_mult.shape, np_mult.dtype))

np_mult (np.multiply(np_b, np_a)); 
[[  0  91 184]
 [279 376 475]
 [576 679 784]]
np_mult.shape = (3, 3), np_mult.dtype = int64

np_mult (np_b * np_a); 
[[  0  91 184]
 [279 376 475]
 [576 679 784]]
np_mult.shape = (3, 3), np_mult.dtype = int64


## Dot product

In [15]:
np_dot = np.dot(np_a, 10)
print("np_dot np.dot(np_a, 10); \n{}".format(np_dot))
print("np_dot.shape = {}, np_dot.dtype = {}".format(np_dot.shape, np_dot.dtype))

np_dot np.dot(np_a, 10); 
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
np_dot.shape = (3, 3), np_dot.dtype = int64


In [16]:
np_dot = np.dot(np_a, np.asarray([10,20,30]))
print("np_dot np.dot(np_a, np.asarray([10,20,30])); \n{}".format(np_dot))
print("np_dot.shape = {}, np_dot.dtype = {}".format(np_dot.shape, np_dot.dtype))

np_dot np.dot(np_a, np.asarray([10,20,30])); 
[ 80 260 440]
np_dot.shape = (3,), np_dot.dtype = int64


In [17]:
np_dot = np.dot(np_a, np_b)
print("np_dot np.dot(np_a, np_b); \n{}".format(np_dot))
print("np_dot.shape = {}, np_dot.dtype = {}".format(np_dot.shape, np_dot.dtype))

np_dot = np.dot(np_b, np_a)
print("\nnp_dot np.dot(np_b, np_a); \n{}".format(np_dot))
print("np_dot.shape = {}, np_dot.dtype = {}".format(np_dot.shape, np_dot.dtype))

np_dot np.dot(np_a, np_b); 
[[ 285  288  291]
 [1122 1134 1146]
 [1959 1980 2001]]
np_dot.shape = (3, 3), np_dot.dtype = int64

np_dot np.dot(np_b, np_a); 
[[ 825 1098 1371]
 [ 852 1134 1416]
 [ 879 1170 1461]]
np_dot.shape = (3, 3), np_dot.dtype = int64


## Division
**NOTE**: conversion to float64 and the runtime warning for divide by zero as well as the "inf" output when a divide by zero is encountered

In [18]:
np_div = np.divide(np_a, np_b)
print("np_div (np.divide(np_a, np_b)); \n{}".format(np_div))
print("np_div.shape = {}, np_div.dtype = {}".format(np_div.shape, np_div.dtype))

np_div = np_a / np_b
print("\nnp_div (np_a / np_b); \n{}".format(np_div))
print("np_div.shape = {}, np_div.dtype = {}".format(np_div.shape, np_div.dtype))

# NOTE: RuntimeWarning: divide by zero encountered in true_divide
np_div = np_b / np_a
print("\nnp_div (np_b / np_a); \n{}".format(np_div))
print("np_div.shape = {}, np_div.dtype = {}".format(np_div.shape, np_div.dtype))

np_div (np.divide(np_a, np_b)); 
[[ 0.          0.01098901  0.02173913]
 [ 0.03225806  0.04255319  0.05263158]
 [ 0.0625      0.07216495  0.08163265]]
np_div.shape = (3, 3), np_div.dtype = float64

np_div (np_a / np_b); 
[[ 0.          0.01098901  0.02173913]
 [ 0.03225806  0.04255319  0.05263158]
 [ 0.0625      0.07216495  0.08163265]]
np_div.shape = (3, 3), np_div.dtype = float64

np_div (np_b / np_a); 
[[         inf  91.          46.        ]
 [ 31.          23.5         19.        ]
 [ 16.          13.85714286  12.25      ]]
np_div.shape = (3, 3), np_div.dtype = float64


/home/jack/anaconda3/envs/tf_cpu/lib/python3.6/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


## Exponent

In [19]:
np_exp = np_a**2
print("np_exp (np_a**2); \n{}".format(np_exp))
print("np_exp.shape = {}, np_exp.dtype = {}".format(np_exp.shape, np_exp.dtype))

np_exp (np_a**2); 
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
np_exp.shape = (3, 3), np_exp.dtype = int64


## Transpose

In [20]:
np_a_t = np.transpose(np_a)
print("np_a; \n{}".format(np_a))
print("\nnp_a_t; \n{}".format(np_a_t))

np_a; 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

np_a_t; 
[[0 3 6]
 [1 4 7]
 [2 5 8]]
