# Numpy Arithmetic

Examples of how to perform basic arithmetic with numpy.  Several of the most common functions, specific to this domain, are shown below.  If you wish to see even more functions and examples please refer to the [documentation](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

## Overview



## To be aware of
> when operating on different types, the resulting type will be the more general or more precise type (upcasting)



**Note**: Please see [numpy_initialization_and_viewing.ipynb](./numpy_initialization_and_viewing.ipynb) for an introduction to numpy as well as links for numpy documentation

In [1]:
import sys
import numpy as np

print("Python: {}".format(sys.version_info[:]))
print('Numpy: {}'.format(np.__version__))

Python: (3, 6, 3, 'final', 0)
Numpy: 1.13.3


In [2]:
np_a = np.arange(9).reshape(3,3)
np_b = np.arange(90,99).reshape(3,3)

print("np_a; \n{}".format(np_a))
print("np_a.shape = {}, np_a.dtype = {}".format(np_a.shape, np_a.dtype))

print("\nnp_b; \n{}".format(np_b))
print("np_b.shape = {}, np_b.dtype = {}".format(np_b.shape, np_b.dtype))

np_a; 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
np_a.shape = (3, 3), np_a.dtype = int64

np_b; 
[[90 91 92]
 [93 94 95]
 [96 97 98]]
np_b.shape = (3, 3), np_b.dtype = int64


## Subtraction

In [3]:
# using np.subtract()
np_sub = np.subtract(np_b, np_a)
print("np_sub (np.subract(np_b, np_a)); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

# using `-` operator
np_sub = np_b - np_a
print("\nnp_sub (np_b - np_a); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))

np_sub (np.subract(np_b, np_a)); 
[[90 90 90]
 [90 90 90]
 [90 90 90]]
np_sub.shape = (3, 3), np_sub.dtype = int64

np_sub (np_b - np_a); 
[[90 90 90]
 [90 90 90]
 [90 90 90]]
np_sub.shape = (3, 3), np_sub.dtype = int64


In [4]:
np_sub = np_b - 10
print("\nnp_sub (np_b - 10); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))


np_sub (np_b - 10); 
[[80 81 82]
 [83 84 85]
 [86 87 88]]
np_sub.shape = (3, 3), np_sub.dtype = int64


In [5]:
# NOTE THE CHANGE TO FLOAT!
np_sub = np_b - 10.
print("\nnp_sub (np_b - 10); \n{}".format(np_sub))
print("np_sub.shape = {}, np_sub.dtype = {}".format(np_sub.shape, np_sub.dtype))


np_sub (np_b - 10); 
[[ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]]
np_sub.shape = (3, 3), np_sub.dtype = float64


## Addition

In [6]:
np_add = np_b + np_a
print("\nnp_add (np_b + np_a); \n{}".format(np_add))
print("np_add.shape = {}, np_add.dtype = {}".format(np_add.shape, np_add.dtype))


np_add (np_b + np_a); 
[[ 90  92  94]
 [ 96  98 100]
 [102 104 106]]
np_add.shape = (3, 3), np_add.dtype = int64
